		<!--
		Name Of Screen: CustomerDeletion.php
		Purpose Of Screen: Form that displays customer details chosen from a given listbox or searchbar as well as a button to delete the chosen customer.
			
		Student Name: Isaiah Andres
		Student Number: C00286361
		Date:10/03/2024 -->
		<!--Main menu file-->
		<?php include 'menu.php'; ?>

			<div class="deletionBox">
			<br>
			<fieldset> <!--Form for the user to see customer details if they choose an option from the listbox. Placement is so that the listbox generated by the following -->  				
			<Form action = "CustomerDeletion.php" method = "POST" name = "searchCustomer" >
			<legend><h1>Customer Deletion Form</h1></legend> <!--Text that displays at the top of the form-->

			<?php include 'customerSearchListbox.php'; ?>
			Use the listbox or the searchbar to search for customers. A second listbox will appear if there are duplicate customers.
			<br>
			<label for="name">Customer Name:</label> <!--Disabled input box in which the customer ID will be displayed-->
            <input type="text" name="custNameID" id="custNameID"/> 
			<div class="submitButton"> <!--Div class for the submit button -->
            <input type="submit" value="Search" name="search" id="search"/><br> <!--Submit button input. Value sets the text within the button and runs the javascript function confirmDeletion upon clicking the submit button -->
			</div>
			</form>
			<?php include 'customerListbox.php'; ?> <!--Customer listbox file -->
			<br><br>

			<form action = "confirmDeletion.php" method = "POST" name = "deletionForm" > <!--Start of the form that displays chosen customer details and submits the information to the confirmDeletion file in which the MySQL statement to set the DeletedFlag to true takes place-->
			
			<div class="customerID"> <!--Div class for the customer's ID label and input box -->
            <label for="name">Customer ID:</label> <!--Disabled input box in which the customer ID will be displayed-->
            <input type="text" name="custID" id="custID" disabled/> 
            </div>
			<br>
            <div class="fname"> <!--Div class for the customer's first name label and input box -->
            <label for="name">Customer First Name:</label> <!--Disabled input box in which the customer first name will be displayed-->
            <input type="text" name="fnameID" id="fnameID"  disabled/>
            </div>
            <br>
			<div class="lname"> <!--Div class for the customer's surname label and input box -->
			<label for="name">Customer Surname:</label> <!--Disabled input box in which the customer surname will be displayed-->
			<input type="text" name="lnameID" id="lnameID"  disabled/>
			</div>
			<br>
            <div class="address">
            <label for="address">Customer Address:</label> <!--Div class for the customer's address label and input box -->
            <input type="text" name="addressID" id="addressID" disabled />  <!--Disabled input box in which the customer address will be displayed-->
            </div>
            <br>
            <div class="eircode">
            <label for="eircode">Customer Eircode:</label> <!--Div class for the customer's eircode label and input box -->
            <input type="text" name="eircodeID" id="eircodeID" disabled/> <!--Disabled input box in which the customer eircode will be displayed-->
            </div>
            <br>
            <div class="DOB">
            <label for="dateOfBirth">Date Of Birth:</label> <!--Div class for the customer's date of birth label and input box -->
            <input type="date" name="dobID" id="dobID" disabled/> <!--Disabled input box in which the customer's date of birth will be displayed-->
            </div>
            <br>
			<div class="phoneNo">
			<label for="phoneNo">Customer Phone Number:</label> <!--Div class for the customer's phone number label and input box -->
			<input type="tel" name="phoneNoID" id="phoneNoID" pattern="[0-9\- \(\) +]{7,}" disabled/> <!--Disabled input box in which the customer phone number will be displayed-->
			</div>
			<br>
			<div class="occupation">
			<label for="occupation">Customer Occupation:</label> <!--Div class for the customer's occupation label and input box -->
			<input type="text" name="occupationID" id="occupationID"disabled/> <!--Disabled input box in which the customer occupation will be displayed-->
			</div>
			<br>
            <div class="salary">
			<label for="salary">Customer Salary:</label> <!--Div class for the customer's salary label and input box -->
			<input type="number" name="salaryID" id="salaryID" min="0" step="0.1" disabled/> <!--Disabled input box in which the customer salary will be displayed-->
			</div>
			<br>
			<div class="email">
			<label for="email">Customer Email:</label> <!--Div class for the customer's email label and input box -->
			<input type="email" name="emailID" id="emailID" disabled/> <!--Disabled input box in which the customer email will be displayed-->
			</div>
			<br>
			<div class="guarantor">
			<label for="guarantor">Guarantor's Name:</label> <!--Div class for the customer's guarantor name label and input box -->
			<input type="text" name="gnameID" id="guarantorID" disabled/> <!--Disabled input box in which the customer's guarantor name will be displayed-->
			</div>
			<br>
            <div class="submitButton"> <!--Div class for the submit button -->
            <input type="submit" value="Delete Customer" name="delete" onclick = "confirmDeletion()" /><br><br> <!--Submit button input. Value sets the text within the button and runs the javascript function confirmDeletion upon clicking the submit button -->
			</div>
            </fieldset>
        </div>
    </form>
	

		</div>
    </body>
</html>